main: club.bruhcraft.DeathCounter
version: '1.0'
api-version: '1.13'
name: 'DeathCounter'
commands:
  topdeaths:
    description: 'Get top deaths on the server'
  getdeaths:
    description: 'Get deaths for a player'